"use client";

import Image from "next/image";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";

type ImageItem = { id: string; fileName: string; imageUrl?: string | null; isOfficial: boolean };
type DriveImage = { id: string; name: string; previewUrl: string };

export function MarketingImageTools({ projectId, contentId, imagePlan, onNotice, onRefresh, onGenerateImagePrompt }: { projectId: string; contentId: string; imagePlan: string; onNotice: (message: string) => void; onRefresh: () => void; onGenerateImagePrompt: (suggestion: string) => Promise<string> }) {
  const [images, setImages] = useState<ImageItem[]>([]);
  const [drive, setDrive] = useState<DriveImage[]>([]);
  const [picker, setPicker] = useState<"suggestion" | "material" | null>(null);
  const [loading, setLoading] = useState(false);
  const [promptOpen, setPromptOpen] = useState(false);
  const [generatedPrompt, setGeneratedPrompt] = useState("");
  const [promptLoading, setPromptLoading] = useState(false);
  const fileRef = useRef<HTMLInputElement>(null);
  const suggestions = useMemo(() => imagePlan.split(/\n+/).map((item) => item.replace(/^\s*(?:[-*•]|\d+[.)])\s*/, "").trim()).filter(Boolean), [imagePlan]);
  const loadImages = useCallback(async () => { const payload = await (await fetch(`/api/marketing-contents?projectId=${projectId}`, { cache: "no-store" })).json(); const work = payload.contents?.find((item: { id: string }) => item.id === contentId); setImages(work?.images ?? []); }, [contentId, projectId]);
  useEffect(() => { const timer = window.setTimeout(() => void loadImages(), 0); return () => window.clearTimeout(timer); }, [loadImages]);
  const upload = async (file: File) => { const form = new FormData(); form.set("projectId", projectId); form.set("file", file); setLoading(true); try { const response = await fetch(`/api/marketing-contents/${contentId}/images`, { method: "POST", body: form }); if (!response.ok) throw new Error("图片上传失败。"); onNotice("图片已加入当前宣传作品"); await loadImages(); onRefresh(); } catch (error) { onNotice(error instanceof Error ? error.message : "图片上传失败。"); } finally { setLoading(false); setPicker(null); } };
  const chooseDrive = async (image: DriveImage) => { try { const response = await fetch(image.previewUrl); const blob = await response.blob(); await upload(new File([blob], image.name, { type: blob.type || "image/*" })); } catch { onNotice("飞书云盘图片读取失败。"); } };
  const openDrive = async () => { setLoading(true); try { const response = await fetch(`/api/agents/design/sources?projectId=${projectId}`, { cache: "no-store" }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || "读取飞书云盘失败。"); setDrive((payload.sources ?? []).filter((item: { kind: string }) => item.kind === "feishu_drive")); } catch (error) { onNotice(error instanceof Error ? error.message : "读取飞书云盘失败。"); } finally { setLoading(false); } };
  const toggleOfficial = async (image: ImageItem, isOfficial: boolean) => { const response = await fetch(`/api/marketing-contents/${contentId}/images`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ projectId, imageId: image.id, isOfficial }) }); if (response.ok) { setImages((current) => current.map((item) => item.id === image.id ? { ...item, isOfficial } : item)); onNotice(isOfficial ? "已设为正式图片" : "已移出正式图片"); } };
  const pick = (kind: "suggestion" | "material") => { setPicker(kind); setDrive([]); };
  const generatePrompt = async (suggestion: string) => { setPromptLoading(true); setPromptOpen(true); setGeneratedPrompt(""); try { const value = await onGenerateImagePrompt(suggestion); setGeneratedPrompt(value || "豆豆暂时没有生成指令，请稍后重试。"); } catch (error) { const message = error instanceof Error ? error.message : "豆豆暂时无法整理图片指令。"; setGeneratedPrompt(""); onNotice(message); setPromptOpen(false); } finally { setPromptLoading(false); } };
  return <div className="mt-3 space-y-3 rounded-lg border border-[#e1e0db] bg-[#fbfbf8] p-3">
    <div><div className="flex items-center justify-between"><h4 className="text-control font-semibold text-[#4a4a44]">豆豆的配图建议</h4><span className="text-caption text-[#999]">每条建议可单独补图</span></div>{suggestions.length === 0 ? <p className="mt-2 text-caption text-[#999]">豆豆还没有给出具体配图建议。</p> : <div className="mt-2 space-y-1.5">{suggestions.map((suggestion, index) => <div key={`${suggestion}-${index}`} className="flex items-center gap-2 rounded border border-[#e9e8e3] bg-white px-2 py-1.5"><span className="min-w-0 flex-1 text-control text-[#56564f]">{suggestion}</span><button type="button" onClick={() => pick("suggestion")} className="rounded border border-[#d5dcd7] px-2 py-1 text-caption text-[#456657]">去上传</button><button type="button" onClick={() => void generatePrompt(suggestion)} className="rounded border border-[#d5dcd7] px-2 py-1 text-caption text-[#456657]">去AI生成</button></div>)}</div>}</div>
    <div><div className="flex items-center justify-between"><h4 className="text-control font-semibold text-[#4a4a44]">图片素材</h4><button type="button" onClick={() => pick("material")} className="text-control text-[#527061]">添加图片</button></div><div className="mt-2 grid grid-cols-2 gap-2">{images.map((image) => <div key={image.id} className={`rounded border p-2 ${image.isOfficial ? "border-[#9dbbaa] bg-[#f3f8f4]" : "border-[#e4e3de] bg-white"}`}>{image.imageUrl ? <Image unoptimized src={image.imageUrl} alt={image.fileName} width={320} height={192} className="h-24 w-full rounded object-cover" /> : <div className="grid h-24 place-items-center text-caption text-[#999]">{image.fileName}</div>}<div className="mt-1 truncate text-caption text-[#666]">{image.fileName}</div><div className="mt-1 flex flex-wrap gap-1"><button type="button" onClick={() => void toggleOfficial(image, !image.isOfficial)} className="rounded border px-1.5 py-1 text-micro">{image.isOfficial ? "移出正式" : "设为正式"}</button>{image.imageUrl ? <><a href={image.imageUrl} target="_blank" rel="noreferrer" className="rounded border px-1.5 py-1 text-micro">看大图</a><a href={image.imageUrl} download={image.fileName} className="rounded border px-1.5 py-1 text-micro">下载</a></> : null}</div></div>)}</div></div>
    <input ref={fileRef} type="file" accept="image/*" className="hidden" onChange={(event) => { const file = event.target.files?.[0]; if (file) void upload(file); event.currentTarget.value = ""; }} />
    {picker && <div className="fixed inset-0 z-50 grid place-items-center bg-black/25 p-4"><div className="w-full max-w-lg rounded-xl bg-white p-4 shadow-xl"><div className="flex items-center justify-between"><h4 className="text-body font-semibold">{picker === "suggestion" ? "为这条配图建议添加图片" : "添加图片素材"}</h4><button type="button" onClick={() => setPicker(null)} className="text-body text-[#999]">×</button></div><div className="mt-3 grid grid-cols-2 gap-2"><button type="button" onClick={() => fileRef.current?.click()} disabled={loading} className="rounded-lg border border-[#dcdcd6] p-4 text-left"><strong className="block text-control">从本地上传</strong><span className="mt-1 block text-caption text-[#999]">选择电脑中的图片</span></button><button type="button" onClick={() => void openDrive()} disabled={loading} className="rounded-lg border border-[#dcdcd6] p-4 text-left"><strong className="block text-control">从项目飞书云盘选择</strong><span className="mt-1 block text-caption text-[#999]">选择已同步的项目图片</span></button></div>{drive.length > 0 && <div className="mt-3 max-h-56 space-y-1 overflow-y-auto">{drive.map((image) => <button key={image.id} type="button" onClick={() => void chooseDrive(image)} className="flex w-full items-center gap-2 rounded border border-[#ecebe7] px-2 py-1.5 text-left"><Image unoptimized src={image.previewUrl} alt="" width={36} height={36} className="h-9 w-9 rounded object-cover" /><span className="min-w-0 flex-1 truncate text-caption">{image.name}</span><span className="text-micro text-[#888]">选择</span></button>)}</div>}</div></div>}
    {promptOpen && <div className="fixed inset-0 z-50 grid place-items-center bg-black/25 p-4"><div className="w-full max-w-xl rounded-xl bg-white p-4 shadow-xl"><div className="flex items-center justify-between"><div><h4 className="text-body font-semibold">生成给小熊的指令</h4><p className="mt-1 text-caption text-[#888]">豆豆只负责生成指令，不会自动发送给小熊。</p></div><button type="button" onClick={() => setPromptOpen(false)} className="text-body text-[#999]">×</button></div><textarea value={generatedPrompt} onChange={(event) => setGeneratedPrompt(event.target.value)} disabled={promptLoading} rows={12} placeholder={promptLoading ? "豆豆正在整理指令…" : "生成的指令会显示在这里"} className="mt-3 w-full resize-y rounded-lg border border-[#dcdcd6] p-3 text-control leading-5 outline-none disabled:bg-[#f6f6f2]" /><div className="mt-3 flex justify-end gap-2"><button type="button" onClick={() => setPromptOpen(false)} className="rounded border border-[#d8d7d1] px-3 py-1.5 text-control">关闭</button><button type="button" disabled={promptLoading || !generatedPrompt.trim()} onClick={() => { void navigator.clipboard.writeText(generatedPrompt); onNotice("给小熊的指令已复制，你可以自行修改后发送"); }} className="rounded bg-[#314a3f] px-3 py-1.5 text-control text-white disabled:opacity-40">复制</button></div></div></div>}
  </div>;
}
